import { z } from "zod";
import type { ArtifactRef } from "../artifact.ts";
import { ArtifactRefSchema } from "../artifact.ts";
import { SourceRefSchema } from "../source.ts";
import { CriterionSchema, DigestStringSchema } from "../step-contract.ts";
import { VerificationResultSchema } from "../verification-result.ts";

/**
 * Payload for the lead.review task — v1.
 *
 * Independence invariant (ADR-0006): this payload must contain NO field
 * carrying a worker session id, conversation transcript, or any other
 * worker-internal context. The reviewer is seeded only with the diff,
 * approved criteria, and verification results.
 *
 * payloadVersion 1 is the default when the field is absent.
 */
export const LeadReviewPayloadSchema = z.object({
  payloadVersion: z.literal(1).optional(),
  attemptId: z.string().min(1),
  generation: z.number().int().min(0),
  contractId: z.string().min(1),
  criteria: z.array(CriterionSchema),
  criteriaDigest: DigestStringSchema,
  profileDigest: DigestStringSchema,
  attemptRevision: z.string().min(1),
  diffDigest: DigestStringSchema,
  /** Path to the patch file in the review worktree. */
  patchPath: z.string().min(1),
  verificationResults: z.array(VerificationResultSchema),
  model: z.string().min(1),
  repoPath: z.string().min(1),
  worktreeBase: z.string().min(1),
  baseRevision: z.string().min(1),
  // NOTE: sessionId and transcript are intentionally absent (ADR-0006 independence).
});
export type LeadReviewPayload = z.infer<typeof LeadReviewPayloadSchema>;
/** Alias for the v1 schema. */
export const LeadReviewPayloadV1Schema = LeadReviewPayloadSchema;
export type LeadReviewPayloadV1 = LeadReviewPayload;

/**
 * Payload for the lead.review task — v2 (portable execution).
 *
 * Host filesystem paths are replaced by portable references:
 * - repoPath + worktreeBase → source: SourceRef
 * - patchPath → patch: ArtifactRef (reviewer materializes diff from artifact)
 *
 * Strict parsing rejects legacy host path fields.
 */
export const LeadReviewPayloadV2Schema = z
  .object({
    payloadVersion: z.literal(2),
    attemptId: z.string().min(1),
    generation: z.number().int().min(0),
    contractId: z.string().min(1),
    criteria: z.array(CriterionSchema),
    criteriaDigest: DigestStringSchema,
    profileDigest: DigestStringSchema,
    attemptRevision: z.string().min(1),
    diffDigest: DigestStringSchema,
    /** Portable artifact reference (replaces patchPath). */
    patch: ArtifactRefSchema,
    verificationResults: z.array(VerificationResultSchema),
    model: z.string().min(1),
    /** Source reference (replaces repoPath + worktreeBase). */
    source: SourceRefSchema,
    baseRevision: z.string().min(1),
    /**
     * Dispatch nonce for lease authentication (D1).
     * Generated by the coordinator at dispatch time; only sha256(nonce) is stored.
     * SECURITY: never log this value.
     */
    leaseNonce: z.string().min(32).optional(),
  })
  .strict();
export type LeadReviewPayloadV2 = z.infer<typeof LeadReviewPayloadV2Schema>;

/**
 * Union of v1 and v2. Use where both formats must be accepted.
 */
export const LeadReviewPayloadAnySchema = z.union([
  LeadReviewPayloadSchema,
  LeadReviewPayloadV2Schema,
]);
export type LeadReviewPayloadAny = z.infer<typeof LeadReviewPayloadAnySchema>;

/** Type guard: returns true iff the payload is a v2 LeadReviewPayload. */
export function isV2Payload(p: LeadReviewPayloadAny): p is LeadReviewPayloadV2 {
  return p.payloadVersion === 2;
}

export type { ArtifactRef };

export const ReviewOutputSchema = z.object({
  reviewer: z.object({
    model: z.string().min(1),
  }),
  subject: z.object({
    attemptRevision: z.string().min(1),
    diffDigest: DigestStringSchema,
    criteriaDigest: DigestStringSchema,
    profileDigest: DigestStringSchema,
  }),
  findings: z.array(
    z.object({
      id: z.string().min(1),
      severity: z.enum(["blocking", "non_blocking"]),
      kind: z.enum([
        "unmet_criterion",
        "weakened_check",
        "verifier_tampered",
        "scope_violation",
        "defect",
        "style",
        "unrelated",
      ]),
      description: z.string(),
      evidence: z.string(),
    }),
  ),
});
export type ReviewOutput = z.infer<typeof ReviewOutputSchema>;
