import { z } from "zod";

import { AuthorityNarrowingSchema, AuthoritySchema } from "../authority.ts";
import { LeadPlanOutputSchema } from "../lead-proposal.ts";
import { ManifestEntrySchema, RevisionManifestSchema } from "../manifest.ts";
import { SourceRefSchema } from "../source.ts";

export type { LeadPlanOutput } from "../lead-proposal.ts";
export { LeadPlanOutputSchema };

/**
 * Payload for the lead.plan task — v1.
 *
 * `authority` is the delegated-authority record for this project/work-item.
 * `narrowing` is an optional per-work-item narrowing of the authority.
 *
 * payloadVersion 1 is the default when the field is absent.
 */
export const LeadPlanPayloadSchema = z.object({
  payloadVersion: z.literal(1).optional(),
  workItemId: z.string().min(1),
  projectId: z.string().min(1),
  repoPath: z.string().min(1),
  baseRevision: z.string().min(1),
  worktreeBase: z.string().min(1),
  /** Delegated-authority record for this project/work-item. */
  authority: AuthoritySchema,
  /** Optional per-work-item narrowing of the authority. */
  narrowing: AuthorityNarrowingSchema.optional(),
  /** Verification profile ids the Lead may select from (project catalog). */
  profileCatalog: z.array(z.string().min(1)).optional(),
  operatorIntent: z.string().min(1),
  /** Optional reproduction of a known defect. */
  defect: z.string().optional(),
  model: z.string().min(1),
  /**
   * Revision manifest for multi-repository WorkItems. The Lead uses this to
   * understand scope and produce contracts that reference the correct target
   * refs and base revisions.
   */
  manifest: RevisionManifestSchema.optional(),
});
export type LeadPlanPayload = z.infer<typeof LeadPlanPayloadSchema>;
/** Alias for the v1 schema. */
export const LeadPlanPayloadV1Schema = LeadPlanPayloadSchema;
export type LeadPlanPayloadV1 = LeadPlanPayload;

// ---------------------------------------------------------------------------
// v2 manifest entry with source per entry
// ---------------------------------------------------------------------------
const ManifestEntryV2Schema = ManifestEntrySchema.extend({
  /** Source reference for this repository's bundle in the coordinator. */
  source: SourceRefSchema,
});

const RevisionManifestV2Schema = z.object({
  entries: z.array(ManifestEntryV2Schema),
  digest: z.string().regex(/^sha256:[0-9a-f]{64}$/),
});

/**
 * Payload for the lead.plan task — v2 (portable execution).
 *
 * Host filesystem paths are replaced by SourceRef. Manifest entries each
 * carry a per-repository source reference. Strict parsing rejects legacy
 * host path fields.
 */
export const LeadPlanPayloadV2Schema = z
  .object({
    payloadVersion: z.literal(2),
    workItemId: z.string().min(1),
    projectId: z.string().min(1),
    /** Source reference (replaces repoPath + worktreeBase). */
    source: SourceRefSchema,
    baseRevision: z.string().min(1),
    authority: AuthoritySchema,
    narrowing: AuthorityNarrowingSchema.optional(),
    profileCatalog: z.array(z.string().min(1)).optional(),
    operatorIntent: z.string().min(1),
    defect: z.string().optional(),
    model: z.string().min(1),
    /** v2 manifest carries source per entry. */
    manifest: RevisionManifestV2Schema.optional(),
    /**
     * Dispatch nonce for lease authentication (D1).
     * Generated by the coordinator at dispatch time; only sha256(nonce) is stored.
     * SECURITY: never log this value.
     */
    leaseNonce: z.string().min(32).optional(),
  })
  .strict();
export type LeadPlanPayloadV2 = z.infer<typeof LeadPlanPayloadV2Schema>;

/**
 * Union of v1 and v2. Use where both formats must be accepted.
 */
export const LeadPlanPayloadAnySchema = z.union([LeadPlanPayloadSchema, LeadPlanPayloadV2Schema]);
export type LeadPlanPayloadAny = z.infer<typeof LeadPlanPayloadAnySchema>;

/** Type guard: returns true iff the payload is a v2 LeadPlanPayload. */
export function isV2Payload(p: LeadPlanPayloadAny): p is LeadPlanPayloadV2 {
  return p.payloadVersion === 2;
}
