import { z } from "zod";

import { RevisionManifestSchema } from "../manifest.ts";
import { SourceRefSchema } from "../source.ts";
import { DigestStringSchema } from "../step-contract.ts";
import { VerificationResultSchema } from "../verification-result.ts";

/**
 * Payload for the verify.run task — v1.
 * payloadVersion 1 is the default when the field is absent.
 */
export const VerifyRunPayloadSchema = z.object({
  payloadVersion: z.literal(1).optional(),
  attemptId: z.string().min(1),
  generation: z.number().int().min(0),
  contractId: z.string().min(1),
  profileId: z.string().min(1),
  profileDigest: DigestStringSchema,
  criteriaDigest: DigestStringSchema,
  repoPath: z.string().min(1),
  worktreeBase: z.string().min(1),
  baseRevision: z.string().min(1),
  attemptRevision: z.string().min(1),
  diffDigest: DigestStringSchema,
  /** Frozen profile protected paths (verifier-tampering detection); the
   * single source of truth for verify.run, copied from the profile by the
   * coordinator. Optional for older payloads: the task then uses the domain
   * default list. */
  protectedPaths: z.array(z.string().min(1)).optional(),
  checks: z.array(
    z.object({
      id: z.string().min(1),
      version: z.string().min(1),
      command: z.array(z.string().min(1)),
      timeoutSeconds: z.number().int().min(1),
    }),
  ),
  /**
   * Revision manifest for multi-repository WorkItems. The verifier uses this
   * to confirm that the attempt revision is consistent with the plan.
   */
  manifest: RevisionManifestSchema.optional(),
});
export type VerifyRunPayload = z.infer<typeof VerifyRunPayloadSchema>;
/** Alias for the v1 schema. */
export const VerifyRunPayloadV1Schema = VerifyRunPayloadSchema;
export type VerifyRunPayloadV1 = VerifyRunPayload;

/**
 * Payload for the verify.run task — v2 (portable execution).
 *
 * Host filesystem paths are replaced by SourceRef. Strict parsing rejects
 * legacy host path fields.
 */
export const VerifyRunPayloadV2Schema = z
  .object({
    payloadVersion: z.literal(2),
    attemptId: z.string().min(1),
    generation: z.number().int().min(0),
    contractId: z.string().min(1),
    profileId: z.string().min(1),
    profileDigest: DigestStringSchema,
    criteriaDigest: DigestStringSchema,
    /** Source reference (replaces repoPath + worktreeBase). */
    source: SourceRefSchema,
    baseRevision: z.string().min(1),
    attemptRevision: z.string().min(1),
    diffDigest: DigestStringSchema,
    protectedPaths: z.array(z.string().min(1)).optional(),
    checks: z.array(
      z.object({
        id: z.string().min(1),
        version: z.string().min(1),
        command: z.array(z.string().min(1)),
        timeoutSeconds: z.number().int().min(1),
      }),
    ),
    manifest: RevisionManifestSchema.optional(),
    /**
     * Dispatch nonce for lease authentication (D1).
     * Generated by the coordinator at dispatch time; only sha256(nonce) is stored.
     * SECURITY: never log this value.
     */
    leaseNonce: z.string().min(32).optional(),
  })
  .strict();
export type VerifyRunPayloadV2 = z.infer<typeof VerifyRunPayloadV2Schema>;

/**
 * Union of v1 and v2. Use where both formats must be accepted.
 */
export const VerifyRunPayloadAnySchema = z.union([
  VerifyRunPayloadSchema,
  VerifyRunPayloadV2Schema,
]);
export type VerifyRunPayloadAny = z.infer<typeof VerifyRunPayloadAnySchema>;

/** Type guard: returns true iff the payload is a v2 VerifyRunPayload. */
export function isV2Payload(p: VerifyRunPayloadAny): p is VerifyRunPayloadV2 {
  return p.payloadVersion === 2;
}

export const VerifyRunIntegritySchema = z.object({
  tamperedPaths: z.array(z.string()),
  protectedPathsSource: z.enum(["payload", "default"]),
});
export type VerifyRunIntegrity = z.infer<typeof VerifyRunIntegritySchema>;

export const VerifyRunOutputSchema = z.object({
  results: z.array(VerificationResultSchema),
  /** Integrity metadata from tamper detection. Optional so older outputs
   * (before H-6) still parse; the coordinator treats absence as a pre-H-6
   * run with no tamper findings. */
  integrity: VerifyRunIntegritySchema.optional(),
});
export type VerifyRunOutput = z.infer<typeof VerifyRunOutputSchema>;
